[package]
name = "jacks-blackjack"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
color-eyre = "0.6.3"
serde_json = "1.0.137"
fakeit = "1.1"
unicode-width = "0.1.14"
itertools = "0.13.0"

