pub const TITLE: &str = concat!(
"\n\n",
"    /$$$$$                     /$$       /$$              /$$$$$$$  /$$                     /$$                               /$$      \n",
"   |__  $$                    | $$      | $/             | $$__  $$| $$                    | $$                              | $$      \n",
"      | $$  /$$$$$$   /$$$$$$$| $$   /$$|_//$$$$$$$      | $$  \\ $$| $$  /$$$$$$   /$$$$$$$| $$   /$$ /$$  /$$$$$$   /$$$$$$$| $$   /$$\n",
"      | $$ |____  $$ /$$_____/| $$  /$$/  /$$_____/      | $$$$$$$ | $$ |____  $$ /$$_____/| $$  /$$/|__/ |____  $$ /$$_____/| $$  /$$/\n",
" /$$  | $$  /$$$$$$$| $$      | $$$$$$/  |  $$$$$$       | $$__  $$| $$  /$$$$$$$| $$      | $$$$$$/  /$$  /$$$$$$$| $$      | $$$$$$/ \n",
"| $$  | $$ /$$__  $$| $$      | $$_  $$   \\____  $$      | $$  \\ $$| $$ /$$__  $$| $$      | $$_  $$ | $$ /$$__  $$| $$      | $$_  $$ \n",
"|  $$$$$$/|  $$$$$$$|  $$$$$$$| $$ \\  $$  /$$$$$$$/      | $$$$$$$/| $$|  $$$$$$$|  $$$$$$$| $$ \\  $$| $$|  $$$$$$$|  $$$$$$$| $$ \\  $$\n",
" \\______/  \\_______/ \\_______/|__/  \\__/ |_______/       |_______/ |__/ \\_______/ \\_______/|__/  \\__/| $$ \\_______/ \\_______/|__/  \\__/\n",
"                                                                                                /$$  | $$                              \n",
"                                                                                               |  $$$$$$/                              \n",
"                                                                                                \\______/                               \n",
);

pub const ABOUT_US: &str = concat!(
"\n\n",
"  /$$$$$$  /$$                             /$$           /$$   /$$           \n",
" /$$__  $$| $$                            | $$          | $$  | $$           \n",
"| $$  \\ $$| $$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$        | $$  | $$  /$$$$$$$ \n",
"| $$$$$$$$| $$__  $$ /$$__  $$| $$  | $$|_  $$_/        | $$  | $$ /$$_____/ \n",
"| $$__  $$| $$  \\ $$| $$  \\ $$| $$  | $$  | $$          | $$  | $$|  $$$$$$  \n",
"| $$  | $$| $$  | $$| $$  | $$| $$  | $$  | $$ /$$      | $$  | $$ \\____  $$ \n",
"| $$  | $$| $$$$$$$/|  $$$$$$/|  $$$$$$/  |  $$$$/      |  $$$$$$/ /$$$$$$$/ \n",
"|__/  |__/|_______/  \\______/  \\______/    \\___/         \\______/ |_______/  \n",
);

pub const ABOUT_US_TEXT: &str = concat!(
"\n\n",
"                                 FREESIDE SOFTWARE                                 \n",
"\n",
"   Named after the orbital paradise from William Gibson's Neuromancer, Freeside    \n",
"   Software was born from a simple idea: the command line doesn't have to feel     \n",
"   like the dystopian underbelly of the digital world.                             \n",
"\n",
"   We're a collective of terminal jockeys who believe that the blinking cursor     \n",
"   is more than just a tool--it's a sanctuary. Remember that feeling when you      \n",
"   first discovered you could bend a computer to your will with nothing but text   \n",
"   commands? That's the magic we're here to preserve and enhance.                  \n",
"\n",
"   Our mission is to transform the humble terminal into something that sparks      \n",
"   joy without sacrificing the power and efficiency that drew us all to the        \n",
"   command line in the first place.                                                \n",
"\n",
"                           JOIN OUR ORBITAL COMMUNITY                           \n",
"\n",
"   Got an idea that would make your terminal experience more delightful? Found     \n",
"   a way to add some flair without bloating the interface? We want to hear from    \n",
"   you.                                                                            \n",
"\n",
"   Our code is open source because we believe the best digital spaces are built    \n",
"   collectively. Fork our repo, submit a pull request, or just drop by our issue   \n",
"   tracker to share your thoughts. Whether you're a veteran console cowboy or a    \n",
"   terminal newbie, your perspective matters.                                      \n",
"\n",
"   Remember: in the spirit of Gibson's high-orbit playground, everyone's invited   \n",
"   to help build this digital getaway--no creds required, just code and creativity. \n",
);